Repository Ktiseos-Nyx/Dataset-Tools, pull requests merged in 2025-01, with the labels that each got.

#13 Parse comfyui and A1111
  .gitignore
  README.md
  __init__.py
  main.py
  metadata_parser.py
  requirements.txt
  test_md_ps.py
  ui.py
Labels: enhancement

#27 Kn/x
  .github/workflows/codacy.yml
  .github/workflows/dependency-review.yml
  .github/workflows/pytest.yml
  CONTRIBUTING.md
  README.md
  _version.py
  dataset_tools/__init__.py
  dataset_tools/access_disk.py
  dataset_tools/correct_types.py
  dataset_tools/logger.py
  dataset_tools/metadata_parser.py
  dataset_tools/ui.py
  dataset_tools/widgets.py
  pyproject.toml
  tests/test_md_ps.py
  tests/test_ui.py
  tests/typetest.py
Labels: enhancement

#30 Update SECURITY.md
  SECURITY.md
Labels: documentation

#31 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#32 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#33 Update README.md
  README.md
Labels: documentation, enhancement

#34 Kn/x
  _version.py
  dataset_tools/access_disk.py
  dataset_tools/correct_types.py
  dataset_tools/logger.py
  dataset_tools/main.py
  dataset_tools/metadata_parser.py
  dataset_tools/ui.py
Labels: enhancement

#35 Kn/x
  .gitignore
  dataset_tools/correct_types.py
  dataset_tools/logger.py
  dataset_tools/metadata_parser.py
  tests/test_md_ps.py
Labels: documentation, enhancement

#51 Update README.md
  README.md
Labels: documentation

#54 Update README.md
  README.md
Labels: documentation

#55 Update README.md
  README.md
Labels: documentation, enhancement, good first issue

#56 Update README.md
  README.md
Labels: documentation, enhancement
